[project]
name = "change"
description = "organizational change for open science"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "linkchecker",
    "mccole"
]

[tool.mccole]
skips = ["*~", "*.pdf", "extras/**", "uv.lock"]
